package printer

import (
	"bytes"
	"context"
	"fmt"
	"log"
	"os"
	"os/exec"
	"strings"
	"time"
)

// PDF printing.
//
// A PDF is a *document*, not a byte stream: handing it to a RAW spooler job
// (StartDocPrinterW datatype "RAW") only works for the rare printer whose
// firmware understands PDF directly. Everything else prints pages of
// gibberish. This file implements a real PDF path:
//
//	validate PDF bytes -> secure temp file (0600, random name, private dir)
//	-> PDF-aware print submission -> wait for completion -> delete temp file
//
// The submission itself is platform specific:
//
//	windows  — ShellExecuteExW with the "printto" verb, i.e. the registered
//	           PDF handler renders the document through the Windows printer
//	           driver (pdf_windows.go). No shell, no string concatenation.
//	all OSes — an explicitly configured PDF helper command
//	           (pdf_print_command in agent.yaml) executed with argv slices.
//	other    — an explicit "not supported" error (pdf_other.go). PDF is never
//	           downgraded to RAW.
const (
	pdfHeaderMarker = "%PDF-"
	pdfEOFMarker    = "%%EOF"
	// The header must appear at the very start of the file; a small window is
	// tolerated only for a UTF-8 BOM / stray whitespace written by exporters.
	pdfHeaderSearchWindow = 64
	// %%EOF is the last token of a well-formed PDF; some writers append a few
	// bytes of padding/newlines after it.
	pdfEOFSearchWindow = 4096
	// Upper bound for one PDF submission (rendering + spooling by the handler).
	defaultPDFPrintTimeout = 120 * time.Second
)

// PDFPrintFunc submits an already-materialized PDF file to a named printer.
// It must block until the submission outcome is known.
type PDFPrintFunc func(ctx context.Context, printerName, pdfPath string) error

// pdfHelperCommand is an optional, explicitly configured PDF helper
// (e.g. SumatraPDF/PDFtoPrinter). It is executed with a real argv slice —
// never through a shell — and only used when configured.
var pdfHelperCommand []string

// SetPDFHelperCommand configures the external PDF print helper. The template
// may contain the placeholders {printer} and {file}; each placeholder is a
// whole argv element, so a printer name can never become extra arguments or
// shell syntax. Passing nil clears the helper.
func SetPDFHelperCommand(argv []string) {
	if len(argv) == 0 {
		pdfHelperCommand = nil
		return
	}
	cp := make([]string, len(argv))
	copy(cp, argv)
	pdfHelperCommand = cp
}

// PDFHelperCommand returns the configured helper argv template (may be nil).
func PDFHelperCommand() []string {
	if pdfHelperCommand == nil {
		return nil
	}
	cp := make([]string, len(pdfHelperCommand))
	copy(cp, pdfHelperCommand)
	return cp
}

// ValidatePDF rejects anything that is not a real, complete PDF document
// before it is written to disk or sent to a printer driver.
func ValidatePDF(data []byte) error {
	if len(data) == 0 {
		return fmt.Errorf("refusing to print empty PDF payload")
	}
	if len(data) > maxPrintBytes {
		return fmt.Errorf("PDF payload %d bytes exceeds %d limit", len(data), maxPrintBytes)
	}
	head := data
	if len(head) > pdfHeaderSearchWindow {
		head = head[:pdfHeaderSearchWindow]
	}
	if !bytes.Contains(head, []byte(pdfHeaderMarker)) {
		return fmt.Errorf("payload is not a PDF document (missing %s header)", pdfHeaderMarker)
	}
	tail := data
	if len(tail) > pdfEOFSearchWindow {
		tail = tail[len(tail)-pdfEOFSearchWindow:]
	}
	if !bytes.Contains(tail, []byte(pdfEOFMarker)) {
		return fmt.Errorf("truncated or malformed PDF document (missing %s trailer)", pdfEOFMarker)
	}
	return nil
}

// ValidatePDFPrinterName rejects printer names that could break out of the
// argument they are placed in (quoting, control characters, absurd lengths).
// Names are always passed as a single argument/quoted parameter — never
// concatenated into a command line interpreted by a shell.
func ValidatePDFPrinterName(name string) error {
	if strings.TrimSpace(name) == "" {
		return fmt.Errorf("printer name is empty")
	}
	if len(name) > 220 {
		return fmt.Errorf("printer name is too long (%d bytes)", len(name))
	}
	for _, r := range name {
		if r < 0x20 || r == 0x7f {
			return fmt.Errorf("printer name contains a control character (0x%02x)", r)
		}
	}
	if strings.ContainsAny(name, "\"") {
		return fmt.Errorf("printer name contains a quote character, which is not a valid Windows printer name")
	}
	return nil
}

// writeSecurePDFTemp materializes the PDF in a private temp directory.
//
// The directory is created with os.MkdirTemp (0700) and the file with
// os.CreateTemp (0600) — both random names generated by the OS API, never
// derived from job/printer/user input, so nothing from the payload can steer
// the path.
func writeSecurePDFTemp(data []byte) (string, func(), error) {
	dir, err := os.MkdirTemp("", "odoo-print-pdf-")
	if err != nil {
		return "", func() {}, fmt.Errorf("create temp dir for PDF: %w", err)
	}
	cleanup := func() {
		if err := os.RemoveAll(dir); err != nil {
			log.Printf("WARNING: failed to remove temporary PDF directory %s: %v", dir, err)
		}
	}

	f, err := os.CreateTemp(dir, "job-*.pdf")
	if err != nil {
		cleanup()
		return "", func() {}, fmt.Errorf("create temp PDF file: %w", err)
	}
	path := f.Name()
	if err := f.Chmod(0o600); err != nil && !isWindowsChmodUnsupported(err) {
		f.Close()
		cleanup()
		return "", func() {}, fmt.Errorf("restrict temp PDF permissions: %w", err)
	}
	if _, err := f.Write(data); err != nil {
		f.Close()
		cleanup()
		return "", func() {}, fmt.Errorf("write temp PDF: %w", err)
	}
	if err := f.Sync(); err != nil {
		f.Close()
		cleanup()
		return "", func() {}, fmt.Errorf("flush temp PDF: %w", err)
	}
	if err := f.Close(); err != nil {
		cleanup()
		return "", func() {}, fmt.Errorf("close temp PDF: %w", err)
	}
	return path, cleanup, nil
}

func isWindowsChmodUnsupported(err error) bool {
	// Windows only supports the read-only bit; a chmod failure there must not
	// abort an otherwise valid print.
	return err != nil && strings.Contains(strings.ToLower(err.Error()), "not supported")
}

// buildPDFHelperArgs expands the configured helper template. Placeholders are
// replaced as WHOLE argv elements: a printer name containing spaces, quotes or
// shell metacharacters stays exactly one argument and is never re-parsed.
func buildPDFHelperArgs(template []string, printerName, pdfPath string) ([]string, error) {
	if len(template) == 0 {
		return nil, fmt.Errorf("no PDF helper command configured")
	}
	out := make([]string, 0, len(template))
	sawFile := false
	for _, part := range template {
		switch part {
		case "{printer}":
			out = append(out, printerName)
		case "{file}":
			out = append(out, pdfPath)
			sawFile = true
		default:
			out = append(out, part)
		}
	}
	if !sawFile {
		return nil, fmt.Errorf("PDF helper command must contain the {file} placeholder")
	}
	return out, nil
}

// runPDFHelper executes the configured helper with an argv slice (exec, not a
// shell) and waits for it to finish so the outcome is known before the temp
// file is deleted.
func runPDFHelper(ctx context.Context, template []string, printerName, pdfPath string) error {
	argv, err := buildPDFHelperArgs(template, printerName, pdfPath)
	if err != nil {
		return err
	}
	cmd := exec.CommandContext(ctx, argv[0], argv[1:]...)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		msg := strings.TrimSpace(stderr.String())
		if msg != "" {
			return fmt.Errorf("PDF helper %s failed: %w: %s", argv[0], err, msg)
		}
		return fmt.Errorf("PDF helper %s failed: %w", argv[0], err)
	}
	return nil
}

// PrintPDF is the shared PDF pipeline used by the PDF-capable backends.
//
// printFn overrides the submission step (used by tests); when nil the
// configured helper command is used, otherwise the platform default.
func PrintPDF(ctx context.Context, printerName string, doc Document, printFn PDFPrintFunc) error {
	if err := ValidatePDF(doc.Data); err != nil {
		return err
	}
	if err := ValidatePDFPrinterName(printerName); err != nil {
		return fmt.Errorf("refusing to print PDF: %w", err)
	}

	if printFn == nil {
		if helper := PDFHelperCommand(); len(helper) > 0 {
			printFn = func(ctx context.Context, name, path string) error {
				return runPDFHelper(ctx, helper, name, path)
			}
		} else {
			printFn = platformPrintPDF
		}
	}

	path, cleanup, err := writeSecurePDFTemp(doc.Data)
	if err != nil {
		return err
	}
	// The temp file is removed on every exit path — success, failure, panic.
	defer cleanup()

	printCtx := ctx
	if _, hasDeadline := ctx.Deadline(); !hasDeadline {
		var cancel context.CancelFunc
		printCtx, cancel = context.WithTimeout(ctx, defaultPDFPrintTimeout)
		defer cancel()
	}

	if err := printFn(printCtx, printerName, path); err != nil {
		return fmt.Errorf("PDF print on %q failed: %w", printerName, err)
	}
	log.Printf("PDF job %s (%d bytes) submitted to printer %q via PDF path", doc.JobID, len(doc.Data), printerName)
	return nil
}
