use serde::{Deserialize, Serialize};
use std::path::Path;
use std::process::Command;

use crate::agent;
use crate::logging;
use crate::paths;

/// Execute a blocking operation (process spawn, sc.exe/tasklist, or the
/// pairing CLI's HTTP round-trip) on Tauri's blocking thread pool. Tauri runs
/// synchronous commands on the main thread, so without this every long action
/// would freeze the WebView2 UI for its entire duration.
async fn run_blocking<T, F>(f: F) -> Result<T, String>
where
    T: Send + 'static,
    F: FnOnce() -> Result<T, String> + Send + 'static,
{
    tauri::async_runtime::spawn_blocking(f)
        .await
        .map_err(|e| format!("background task failed: {e}"))?
}

#[derive(Serialize)]
pub struct AgentStatus {
    pub running: bool,
    pub service: String,
    pub version: String,
    pub hostname: String,
    pub last_heartbeat: Option<String>,
    pub ws_connected: bool,
    pub note: String,
}

#[tauri::command]
pub async fn get_agent_status(app: tauri::AppHandle) -> AgentStatus {
    let hostname = std::env::var("COMPUTERNAME")
        .or_else(|_| std::env::var("HOSTNAME"))
        .unwrap_or_else(|_| "unknown".into());
    let base = AgentStatus {
        running: false,
        service: "OdooPrintAgent".into(),
        version: env!("CARGO_PKG_VERSION").into(),
        hostname,
        last_heartbeat: None,
        ws_connected: false,
        note: String::new(),
    };
    // `sc query` + `tasklist` are fast but still subprocess I/O; keep them off
    // the UI thread for consistency with the rest of the command surface.
    match tauri::async_runtime::spawn_blocking(move || agent::status(&app)).await {
        Ok((running, _service_running, note)) => AgentStatus {
            running,
            ws_connected: running,
            note,
            ..base
        },
        Err(e) => AgentStatus {
            note: format!("status check failed: {e}"),
            ..base
        },
    }
}

#[tauri::command]
pub async fn start_agent(app: tauri::AppHandle) -> Result<String, String> {
    run_blocking(move || agent::start(&app)).await.map(|_| "agent started".into())
}

#[tauri::command]
pub async fn stop_agent(app: tauri::AppHandle) -> Result<String, String> {
    run_blocking(move || agent::stop(&app)).await.map(|_| "agent stopped".into())
}

#[tauri::command]
pub async fn restart_agent(app: tauri::AppHandle) -> Result<String, String> {
    run_blocking(move || agent::restart(&app)).await.map(|_| "agent restarted".into())
}

#[tauri::command]
pub async fn control_service(action: String, app: tauri::AppHandle) -> Result<String, String> {
    run_blocking(move || agent::control_service(&action, &app)).await
}

#[derive(Deserialize)]
pub struct PairArgs {
    pub code: String,
    pub gateway_url: String,
}

/// Pairing codes are generated by the gateway as 6 characters from an
/// unambiguous alphabet (no O/I, no 0/1) — mirror of the gateway contract.
fn is_valid_code(s: &str) -> bool {
    let t = s.trim().to_uppercase();
    t.len() == 6
        && t.chars()
            .all(|c| matches!(c, 'A'..='H' | 'J'..='N' | 'P'..='Z' | '2'..='9'))
}

#[tauri::command]
pub async fn pair_agent(args: PairArgs, app: tauri::AppHandle) -> Result<String, String> {
    // Cheap validation happens before dispatching to the blocking pool so the
    // UI gets immediate feedback on malformed input.
    let code = args.code.trim().to_uppercase();
    if !is_valid_code(&code) {
        return Err("pairing code must be a 6-character code from the dashboard (letters without O/I and digits without 0/1)".into());
    }
    let gateway_url = args.gateway_url.trim().trim_end_matches('/').to_string();
    if !(gateway_url.starts_with("https://") || gateway_url.starts_with("http://")) {
        return Err("gateway_url must be https:// or http://".into());
    }
    run_blocking(move || run_pairing(app, &code, &gateway_url)).await
}

/// The actual pairing: invokes the bundled CLI, which performs the HTTPS
/// register call and writes the credentials to the agent config. The returned
/// stdout only contains the agent id by CLI contract — never the secret.
fn run_pairing(app: tauri::AppHandle, code: &str, gateway_url: &str) -> Result<String, String> {
    let cli = agent::cli_path(&app)?;
    let config = paths::agent_config_path();
    paths::ensure_agent_data_root()
        .map_err(|e| format!("create agent data dir: {e}"))?;

    logging::info(&format!("pairing agent (server={gateway_url})"));
    let out = Command::new(&cli)
        .arg("-pair")
        .arg(code)
        .arg("-server")
        .arg(gateway_url)
        .arg("-config")
        .arg(&config)
        .env("ODOO_PRINT_AGENT_DATA_DIR", paths::agent_data_root())
        .output()
        .map_err(|e| format!("failed to run odoo-agent-cli.exe: {e}"))?;

    let stdout = String::from_utf8_lossy(&out.stdout).trim().to_string();
    let stderr = String::from_utf8_lossy(&out.stderr).trim().to_string();
    if !out.status.success() {
        let msg = if stderr.is_empty() { stdout } else { stderr };
        logging::error(&format!("pairing failed: {msg}"));
        return Err(msg);
    }
    // Do not echo anything that could contain the secret. Register only prints
    // the agent id and a success hint; keep that contract on the Rust side.
    logging::info(&format!("pairing succeeded: {stdout}"));
    Ok(stdout)
}

#[derive(Serialize, Deserialize, Clone)]
pub struct GatewayConfig {
    pub url: String,
}

fn read_file_or_default(path: &Path) -> Result<String, String> {
    match std::fs::read_to_string(path) {
        Ok(s) => Ok(s),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok("{}".into()),
        Err(e) => Err(format!("failed to read settings {}: {e}", path.display())),
    }
}

#[tauri::command]
pub fn get_gateway_config() -> GatewayConfig {
    let path = paths::settings_path();
    let defaults = GatewayConfig { url: String::new() };
    let raw = match read_file_or_default(&path) {
        Ok(r) => r,
        Err(e) => {
            logging::error(&e);
            return defaults;
        }
    };
    match serde_json::from_str::<GatewayConfig>(&raw) {
        Ok(c) => c,
        Err(e) => {
            // A corrupt/old settings file must not prevent the app from starting.
            logging::warn(&format!("settings corrupted, using defaults: {e}; path={}", path.display()));
            defaults
        }
    }
}

#[tauri::command]
pub fn set_gateway_config(url: String) -> Result<String, String> {
    let url = url.trim().trim_end_matches('/').to_string();
    if !(url.starts_with("https://") || url.starts_with("http://")) {
        return Err("url must be https:// or http://".into());
    }
    let path = paths::settings_path();
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("create settings dir: {e}"))?;
    }
    let cfg = GatewayConfig { url };
    let json = serde_json::to_string_pretty(&cfg)
        .map_err(|e| format!("serialize settings: {e}"))?;
    std::fs::write(&path, json)
        .map_err(|e| format!("write settings {}: {e}", path.display()))?;
    logging::info(&format!("gateway settings saved to {}", path.display()));
    Ok(format!("saved gateway settings to {}", path.display()))
}

#[derive(Serialize)]
pub struct RuntimePaths {
    pub manager_data: String,
    pub settings: String,
    pub agent_config: String,
    pub manager_log: String,
    pub agent_data: String,
}

#[tauri::command]
pub fn get_runtime_paths() -> RuntimePaths {
    RuntimePaths {
        manager_data: paths::manager_data_root().display().to_string(),
        settings: paths::settings_path().display().to_string(),
        agent_config: paths::agent_config_path().display().to_string(),
        manager_log: paths::manager_log_path().display().to_string(),
        agent_data: paths::agent_data_root().display().to_string(),
    }
}

#[tauri::command]
pub fn get_app_version() -> String {
    env!("CARGO_PKG_VERSION").into()
}
