use serde::{Deserialize, Serialize};
use std::path::Path;
use std::process::Command;

use crate::agent;
use crate::logging;
use crate::paths;

/// Execute a blocking operation (process spawn, sc.exe/tasklist, or the
/// pairing CLI's HTTP round-trip) on Tauri's blocking thread pool. Tauri runs
/// synchronous commands on the main thread, so without this every long action
/// would freeze the WebView2 UI for its entire duration.
async fn run_blocking<T, F>(f: F) -> Result<T, String>
where
    T: Send + 'static,
    F: FnOnce() -> Result<T, String> + Send + 'static,
{
    tauri::async_runtime::spawn_blocking(f)
        .await
        .map_err(|e| format!("background task failed: {e}"))?
}

#[derive(Serialize)]
pub struct AgentStatus {
    pub running: bool,
    pub service: String,
    pub version: String,
    pub hostname: String,
    pub note: String,
}

#[tauri::command]
pub async fn get_agent_status(app: tauri::AppHandle) -> AgentStatus {
    let hostname = std::env::var("COMPUTERNAME")
        .or_else(|_| std::env::var("HOSTNAME"))
        .unwrap_or_else(|_| "unknown".into());
    let base = AgentStatus {
        running: false,
        service: "OdooPrintAgent".into(),
        version: env!("CARGO_PKG_VERSION").into(),
        hostname,
        note: String::new(),
    };
    // `sc query` + `tasklist` are fast but still subprocess I/O; keep them off
    // the UI thread for consistency with the rest of the command surface.
    //
    // Only LOCAL process/service state is reported here. The agent's gateway
    // WS-connection state and last heartbeat live on the Gateway (the desktop
    // has no manager credential to query them), so they are deliberately NOT
    // included — no invented values.
    match tauri::async_runtime::spawn_blocking(move || agent::status(&app)).await {
        Ok((running, _service_running, note)) => AgentStatus {
            running,
            note,
            ..base
        },
        Err(e) => AgentStatus {
            note: format!("status check failed: {e}"),
            ..base
        },
    }
}

#[tauri::command]
pub async fn start_agent(app: tauri::AppHandle) -> Result<String, String> {
    run_blocking(move || agent::start(&app)).await.map(|_| "agent started".into())
}

#[tauri::command]
pub async fn stop_agent(app: tauri::AppHandle) -> Result<String, String> {
    run_blocking(move || agent::stop(&app)).await.map(|_| "agent stopped".into())
}

#[tauri::command]
pub async fn restart_agent(app: tauri::AppHandle) -> Result<String, String> {
    run_blocking(move || agent::restart(&app)).await.map(|_| "agent restarted".into())
}

#[tauri::command]
pub async fn control_service(action: String, app: tauri::AppHandle) -> Result<String, String> {
    run_blocking(move || agent::control_service(&action, &app)).await
}

#[derive(Deserialize)]
pub struct PairArgs {
    pub code: String,
    pub gateway_url: String,
}

fn normalize_gateway_url(raw: &str) -> Result<String, String> {
    let url = raw.trim();
    if url.is_empty() {
        return Err("gateway URL cannot be empty".into());
    }
    if url.contains(char::is_whitespace) {
        return Err("gateway URL cannot contain whitespace".into());
    }
    let parsed = url.parse::<url::Url>().map_err(|e| format!("invalid gateway URL: {e}"))?;
    let scheme = parsed.scheme();
    if !(scheme == "http" || scheme == "https") {
        return Err("gateway URL must use http:// or https://".into());
    }
    if parsed.username() != "" || parsed.password().is_some() {
        return Err("gateway URL cannot include embedded credentials".into());
    }
    if parsed.query().is_some() || parsed.fragment().is_some() {
        return Err("gateway URL cannot include query strings or fragments".into());
    }
    Ok(parsed.as_str().trim_end_matches('/').to_string())
}

/// Pairing codes are generated by the gateway as 6 characters from an
/// unambiguous alphabet (no O/I, no 0/1) — mirror of the gateway contract.
fn is_valid_code(s: &str) -> bool {
    let t = s.trim().to_uppercase();
    t.len() == 6
        && t.chars()
            .all(|c| matches!(c, 'A'..='H' | 'J'..='N' | 'P'..='Z' | '2'..='9'))
}

#[tauri::command]
pub async fn pair_agent(args: PairArgs, app: tauri::AppHandle) -> Result<String, String> {
    // Cheap validation happens before dispatching to the blocking pool so the
    // UI gets immediate feedback on malformed input.
    let code = args.code.trim().to_uppercase();
    if !is_valid_code(&code) {
        return Err("pairing code must be a 6-character code from the dashboard (letters without O/I and digits without 0/1)".into());
    }
    let gateway_url = normalize_gateway_url(&args.gateway_url)?;
    run_blocking(move || run_pairing(app, &code, &gateway_url)).await
}

/// The actual pairing: invokes the bundled CLI, which performs the HTTPS
/// register call and writes the credentials to the agent config. The returned
/// stdout only contains the agent id by CLI contract — never the secret.
fn run_pairing(app: tauri::AppHandle, code: &str, gateway_url: &str) -> Result<String, String> {
    let cli = agent::cli_path(&app)?;
    let config = paths::agent_config_path();
    paths::ensure_agent_data_root()
        .map_err(|e| format!("create agent data dir: {e}"))?;

    logging::info(&format!("pairing agent (server={gateway_url})"));
    let mut cmd = Command::new(&cli);
    cmd.arg("-pair")
        .arg(code)
        .arg("-server")
        .arg(gateway_url)
        .arg("-config")
        .arg(&config)
        .env("ODOO_PRINT_AGENT_DATA_DIR", paths::agent_data_root());
    #[cfg(windows)]
    {
        use std::os::windows::process::CommandExt;
        cmd.creation_flags(0x0800_0000);
    }
    let out = cmd
        .output()
        .map_err(|e| format!("failed to run odoo-agent-cli.exe: {e}"))?;

    let stdout = String::from_utf8_lossy(&out.stdout).trim().to_string();
    let stderr = String::from_utf8_lossy(&out.stderr).trim().to_string();
    if !out.status.success() {
        let msg = if stderr.is_empty() { stdout } else { stderr };
        logging::error(&format!("pairing failed: {msg}"));
        return Err(msg);
    }
    // Do not echo anything that could contain the secret. Register only prints
    // the agent id and a success hint; keep that contract on the Rust side.
    logging::info(&format!("pairing succeeded: {stdout}"));
    Ok(stdout)
}

#[derive(Serialize, Deserialize, Clone)]
pub struct GatewayConfig {
    pub url: String,
}

fn read_file_or_default(path: &Path) -> Result<String, String> {
    match std::fs::read_to_string(path) {
        Ok(s) => Ok(s),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok("{}".into()),
        Err(e) => Err(format!("failed to read settings {}: {e}", path.display())),
    }
}

#[tauri::command]
pub fn get_gateway_config() -> GatewayConfig {
    let path = paths::settings_path();
    let defaults = GatewayConfig { url: String::new() };
    let raw = match read_file_or_default(&path) {
        Ok(r) => r,
        Err(e) => {
            logging::error(&e);
            return defaults;
        }
    };
    match serde_json::from_str::<GatewayConfig>(&raw) {
        Ok(c) => c,
        Err(e) => {
            // A corrupt/old settings file must not prevent the app from starting.
            logging::warn(&format!("settings corrupted, using defaults: {e}; path={}", path.display()));
            defaults
        }
    }
}

#[tauri::command]
pub fn set_gateway_config(url: String) -> Result<String, String> {
    let url = normalize_gateway_url(&url)?;
    let path = paths::settings_path();
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("create settings dir: {e}"))?;
    }
    let cfg = GatewayConfig { url };
    let json = serde_json::to_string_pretty(&cfg)
        .map_err(|e| format!("serialize settings: {e}"))?;
    std::fs::write(&path, json)
        .map_err(|e| format!("write settings {}: {e}", path.display()))?;
    logging::info(&format!("gateway settings saved to {}", path.display()));
    Ok(format!("saved gateway settings to {}", path.display()))
}

#[derive(Serialize)]
pub struct RuntimePaths {
    pub manager_data: String,
    pub settings: String,
    pub agent_config: String,
    pub manager_log: String,
    pub agent_data: String,
}

#[tauri::command]
pub fn get_runtime_paths() -> RuntimePaths {
    RuntimePaths {
        manager_data: paths::manager_data_root().display().to_string(),
        settings: paths::settings_path().display().to_string(),
        agent_config: paths::agent_config_path().display().to_string(),
        manager_log: paths::manager_log_path().display().to_string(),
        agent_data: paths::agent_data_root().display().to_string(),
    }
}

#[tauri::command]
pub fn get_app_version() -> String {
    env!("CARGO_PKG_VERSION").into()
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct PrinterInfo {
    pub id: String,
    pub name: String,
    #[serde(rename = "displayName", alias = "display_name")]
    pub display_name: Option<String>,
    #[serde(rename = "printerType", alias = "printer_type")]
    pub printer_type: Option<String>,
    #[serde(rename = "connectionType", alias = "connection_type")]
    pub connection_type: Option<String>,
    pub protocol: Option<String>,
    pub endpoint: Option<String>,
    #[serde(rename = "spoolerName", alias = "spooler_name")]
    pub spooler_name: Option<String>,
    #[serde(rename = "networkAddress", alias = "network_address")]
    pub network_address: Option<String>,
    pub port: Option<i32>,
    pub status: String,
    pub enabled: bool,
    #[serde(rename = "isVirtual", alias = "is_virtual")]
    pub isVirtual: Option<bool>,
    #[serde(rename = "usbVid")]
    pub usb_vid: Option<String>,
    #[serde(rename = "usbPid")]
    pub usb_pid: Option<String>,
    #[serde(rename = "usbSerial")]
    pub usb_serial: Option<String>,
    pub capabilities: Option<serde_json::Value>,
}

#[derive(Serialize)]
pub struct DiscoverResult {
    pub printers: Vec<PrinterInfo>,
    pub errors: Vec<String>,
}

/// Virtual / software / RDP-redirected queue detection — desktop safety net.
///
/// The authoritative filter is the Windows agent, which classifies every queue
/// during discovery (port monitor, driver, PnP ids, transport) and never
/// registers a non-physical printer. This only guards the UI against a record
/// that an older version already persisted.
/// Windows port monitors whose output never reaches hardware: they write a
/// file, discard the job or dial a modem. This is device metadata (like the
/// agent's `virtualPortMonitors`), not a printer name.
const VIRTUAL_PORT_MONITORS: &[&str] = &[
    "portprompt:", // Microsoft Print to PDF / print-to-file prompt
    "xpsport:",    // Microsoft XPS Document Writer
    "file:",       // print to file
    "nul:",
    "null:",
    "shrfax:", // Windows Shared Fax
    "fax:",
];

/// Driver / PnP families that only ever produce a file or hand the job to an
/// application. Mirrors the Windows agent's `softwareWriterTokens`.
const SOFTWARE_WRITER_TOKENS: &[&str] = &[
    // Microsoft in-box software writers
    "microsoft print to pdf",
    "microsoft xps document writer",
    "microsoft shared fax",
    "microsoft enhanced point and print compatibility driver",
    "send to onenote",
    "onenote",
    // Semantic families (language independent)
    "document writer",
    "documentwriter",
    "print to pdf",
    "topdf",
    "pdf writer",
    "pdfwriter",
    "pdf printer",
    "pdf creator",
    "pdf converter",
    "pdf architect",
    "virtual printer",
    "software printer",
    "image printer",
    // Widely deployed third-party software writers
    "foxit",
    "anydesk",
    "cutepdf",
    "pdf995",
    "novapdf",
    "bullzip",
    "pdfcreator",
    "pdfforge",
    "doro pdf",
    "biopdf",
    "nitro pdf",
    "adobe pdf",
    "bluebeam",
    "tinypdf",
    "7-pdf",
    "icecream pdf",
    "pdf24",
];

/// Queues tunnelled from another desktop session. Mirrors the agent's
/// `sessionRedirectTokens`.
const SESSION_REDIRECT_TOKENS: &[&str] = &[
    "remote desktop easy print",
    "terminal services easy print",
    "ts easy print",
    "easy print",
    "citrix",
    "vmware virtual print",
    "thinprint",
    "safeguard print",
];

fn is_virtual_printer_for_ui(p: &PrinterInfo) -> bool {
    if p.isVirtual.unwrap_or(false) {
        return true;
    }
    if let Some(t) = p.printer_type.as_ref() {
        if t.trim().to_lowercase() == "virtual" {
            return true;
        }
    }
    if let Some(c) = p.connection_type.as_ref() {
        if c.trim().to_lowercase() == "virtual" {
            return true;
        }
    }
    if let Some(proto) = p.protocol.as_ref() {
        if proto.trim().to_lowercase() == "virtual" {
            return true;
        }
    }

    let caps = p.capabilities.as_ref();
    if let Some(caps) = caps {
        for key in ["virtual", "is_virtual"].iter() {
            if caps.get(*key).and_then(|v| v.as_bool()) == Some(true) {
                return true;
            }
        }
        let class = caps
            .get("printer_class")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_lowercase();
        if class == "virtual" || class == "redirected" {
            return true;
        }
        // Port monitor. "IP_192.168.1.50,SNMP" -> "ip_192.168.1.50".
        if let Some(port) = caps.get("port_name").and_then(|v| v.as_str()) {
            let lowered = port.to_lowercase();
            let head = lowered.split(',').next().unwrap_or("").trim();
            if VIRTUAL_PORT_MONITORS
                .iter()
                .any(|m| head == *m || head.starts_with(m))
            {
                return true;
            }
        }
    }

    let name_lower = p.name.to_lowercase();
    // Windows: "HP LaserJet (redirected 3)". Citrix: "… (from WKS12) in session 4".
    if name_lower.contains("(redirected") || name_lower.contains(" in session ") {
        return true;
    }

    // The driver, the comment and the PnP ids identify a software writer or a
    // session tunnel far more reliably than the display name does.
    let mut hay = String::new();
    if let Some(caps) = caps {
        for key in ["driver_name", "comment", "device_id"].iter() {
            if let Some(v) = caps.get(*key).and_then(|v| v.as_str()) {
                hay.push(' ');
                hay.push_str(&v.to_lowercase());
            }
        }
        for key in ["hardware_ids", "compatible_ids"].iter() {
            if let Some(list) = caps.get(*key).and_then(|v| v.as_array()) {
                for item in list {
                    if let Some(v) = item.as_str() {
                        hay.push(' ');
                        hay.push_str(&v.to_lowercase());
                    }
                }
            }
        }
    }
    hay.push(' ');
    hay.push_str(&name_lower);

    if SOFTWARE_WRITER_TOKENS.iter().any(|t| hay.contains(t)) {
        return true;
    }
    SESSION_REDIRECT_TOKENS.iter().any(|t| hay.contains(t))
}

fn is_valid_printer_for_ui(p: &PrinterInfo) -> bool {
    // Virtual, software and redirected queues are never production printers.
    if is_virtual_printer_for_ui(p) {
        return false;
    }
    let name_lower = p.name.to_lowercase();
    let driver_lower = p.capabilities.as_ref()
        .and_then(|v| v.get("driver_name").and_then(|x| x.as_str()))
        .unwrap_or("")
        .to_lowercase();
    let combined = format!("{} {}", name_lower, driver_lower);
    let generic = [
        "usb input device",
        "usb composite device",
        "hid-compliant",
        "hid compliant",
        "standard system devices",
        "standard usb host controller",
        "intel(r) wireless bluetooth",
        "wireless bluetooth",
        "bluetooth adapter",
        "fingerprint sensor",
        "touch fingerprint",
        "synaptics",
        "vfs7552",
        "hd camera",
        "hp hd camera",
        "camera",
        "usb hub",
        "generic usb hub",
    ];
    for g in generic {
        if combined.contains(g) {
            // Allow if driver explicitly says printer (check "printer" not "print" to avoid fingerprint)
            if driver_lower.contains("printer") || driver_lower.contains("laser") || driver_lower.contains("inkjet") || driver_lower.contains("thermal") || driver_lower.contains("label") || driver_lower.contains("zebra") {
                continue;
            }
            return false;
        }
    }
    true
}

#[tauri::command]
pub async fn get_printers(app: tauri::AppHandle) -> Result<Vec<PrinterInfo>, String> {
    run_blocking(move || {
        let path = paths::agent_data_root().join("printers.json");
        if !path.exists() {
            return Ok(vec![]);
        }
        let raw = std::fs::read_to_string(&path).map_err(|e| format!("read {}: {}", path.display(), e))?;
        if raw.trim().is_empty() {
            return Ok(vec![]);
        }
        let v: Vec<PrinterInfo> = serde_json::from_str(&raw).map_err(|e| format!("parse {}: {}", path.display(), e))?;
        let filtered: Vec<PrinterInfo> = v.into_iter().filter(|p| is_valid_printer_for_ui(p)).collect();
        Ok(filtered)
    })
    .await
}

#[tauri::command]
pub async fn discover_printers(app: tauri::AppHandle) -> Result<DiscoverResult, String> {
    run_blocking(move || {
        let cli = agent::cli_path(&app)?;
        let config = paths::agent_config_path();
        let root = paths::agent_data_root();
        let _ = paths::ensure_agent_data_root().map_err(|e| format!("create agent data dir: {}", e))?;
        let mut discover_cmd = std::process::Command::new(&cli);
        discover_cmd
            .arg("printers")
            .arg("discover")
            .arg("--json")
            .arg("-config")
            .arg(&config)
            .env("ODOO_PRINT_AGENT_DATA_DIR", &root);
        #[cfg(windows)]
        {
            use std::os::windows::process::CommandExt;
            discover_cmd.creation_flags(0x0800_0000);
        }
        let out = discover_cmd
            .output()
            .map_err(|e| format!("failed to run discover: {}", e))?;
        let stdout = String::from_utf8_lossy(&out.stdout).to_string();
        let stderr = String::from_utf8_lossy(&out.stderr).to_string();
        if !out.status.success() {
            let msg = if stderr.trim().is_empty() { stdout.clone() } else { stderr.clone() };
            return Err(format!("discover failed: {}", msg));
        }
        // CLI prints table; also try to read printers.json for structured result
        let printers = {
            let p = root.join("printers.json");
            if p.exists() {
                let raw = std::fs::read_to_string(&p).unwrap_or_default();
                let v: Vec<PrinterInfo> = serde_json::from_str::<Vec<PrinterInfo>>(&raw).unwrap_or_default();
                v.into_iter().filter(|x| is_valid_printer_for_ui(x)).collect::<Vec<_>>()
            } else {
                vec![]
            }
        };
        Ok(DiscoverResult { printers, errors: if stderr.is_empty() { vec![] } else { vec![stderr] } })
    })
    .await
}

#[tauri::command]
pub async fn test_printer(printer_id: String, app: tauri::AppHandle) -> Result<String, String> {
    if printer_id.trim().is_empty() {
        return Err("printer id is required".into());
    }
    let pid = printer_id.clone();
    run_blocking(move || {
        let cli = agent::cli_path(&app)?;
        let config = paths::agent_config_path();
        let root = paths::agent_data_root();
        let mut test_cmd = std::process::Command::new(&cli);
        test_cmd
            .arg("printers")
            .arg("test")
            .arg(&pid)
            .arg("-config")
            .arg(&config)
            .env("ODOO_PRINT_AGENT_DATA_DIR", &root);
        #[cfg(windows)]
        {
            use std::os::windows::process::CommandExt;
            test_cmd.creation_flags(0x0800_0000);
        }
        let out = test_cmd
            .output()
            .map_err(|e| format!("failed to run test: {}", e))?;
        let stdout = String::from_utf8_lossy(&out.stdout).trim().to_string();
        let stderr = String::from_utf8_lossy(&out.stderr).trim().to_string();
        if !out.status.success() {
            let msg = if stderr.is_empty() { stdout } else { stderr };
            return Err(msg);
        }
        Ok(stdout)
    })
    .await
}

#[derive(Deserialize, Debug)]
pub struct RegisterPrinterRequest {
    pub name: String,
    pub connectionType: String,
    #[serde(rename = "connection_type")]
    pub connection_type_alt: Option<String>,
    pub endpoint: Option<String>,
    #[serde(rename = "spoolerName")]
    pub spooler_name: Option<String>,
    pub protocol: Option<String>,
    #[serde(rename = "printerType")]
    pub printer_type: Option<String>,
    #[serde(rename = "usbVid")]
    pub usb_vid: Option<String>,
    #[serde(rename = "usbPid")]
    pub usb_pid: Option<String>,
    #[serde(rename = "usbSerial")]
    pub usb_serial: Option<String>,
}

#[tauri::command]
pub async fn register_printer(request: RegisterPrinterRequest, app: tauri::AppHandle) -> Result<String, String> {
    let name = request.name.trim().to_string();
    if name.is_empty() {
        return Err("printer name is required".into());
    }
    let conn = request.connection_type_alt.clone().unwrap_or(request.connectionType.clone());
    let conn_lower = conn.trim().to_lowercase();
    let valid_conns = ["spooler", "network", "tcp", "usb", "ipp", "ipps"];
    if !valid_conns.contains(&conn_lower.as_str()) {
        return Err("connection type must be spooler, network, usb, or ipp".into());
    }
    run_blocking(move || {
        let cli = agent::cli_path(&app)?;
        let config = paths::agent_config_path();
        let root = paths::agent_data_root();
        let mut cmd = std::process::Command::new(&cli);
        cmd.arg("printers").arg("add").arg("--name").arg(&name).arg("--type").arg(&conn_lower);
        if let Some(ep) = request.endpoint.as_ref().filter(|s| !s.trim().is_empty()) {
            cmd.arg("--endpoint").arg(ep.trim());
        }
        if let Some(sn) = request.spooler_name.as_ref().filter(|s| !s.trim().is_empty()) {
            cmd.arg("--spooler-name").arg(sn.trim());
        }
        if let Some(proto) = request.protocol.as_ref().filter(|s| !s.trim().is_empty()) {
            cmd.arg("--protocol").arg(proto.trim().to_lowercase());
        }
        if let Some(pt) = request.printer_type.as_ref().filter(|s| !s.trim().is_empty()) {
            cmd.arg("--printer-type").arg(pt.trim().to_lowercase());
        }
        if let Some(vid) = request.usb_vid.as_ref().filter(|s| !s.trim().is_empty()) {
            cmd.arg("--vid").arg(vid.trim());
        }
        if let Some(pid) = request.usb_pid.as_ref().filter(|s| !s.trim().is_empty()) {
            cmd.arg("--pid").arg(pid.trim());
        }
        if let Some(serial) = request.usb_serial.as_ref().filter(|s| !s.trim().is_empty()) {
            cmd.arg("--serial").arg(serial.trim());
        }
        cmd.arg("-config").arg(&config);
        cmd.env("ODOO_PRINT_AGENT_DATA_DIR", &root);
        #[cfg(windows)]
        {
            use std::os::windows::process::CommandExt;
            cmd.creation_flags(0x0800_0000);
        }
        let out = cmd.output().map_err(|e| format!("failed to run register: {}", e))?;
        let stdout = String::from_utf8_lossy(&out.stdout).trim().to_string();
        let stderr = String::from_utf8_lossy(&out.stderr).trim().to_string();
        if !out.status.success() {
            let msg = if stderr.is_empty() { stdout } else { stderr };
            return Err(msg);
        }
        if stdout.is_empty() {
            Ok(format!("Printer '{}' added", name))
        } else {
            Ok(stdout)
        }
    })
    .await
}

#[derive(Serialize, Clone)]
pub struct AutostartStatus {
    pub enabled: bool,
}

#[tauri::command]
pub async fn get_autostart(app: tauri::AppHandle) -> Result<AutostartStatus, String> {
    run_blocking(move || {
        #[cfg(windows)]
        {
            use tauri_plugin_autostart::ManagerExt;
            let enabled = app.autolaunch().is_enabled().unwrap_or(false);
            Ok(AutostartStatus { enabled })
        }
        #[cfg(not(windows))]
        {
            let _ = &app;
            Ok(AutostartStatus { enabled: false })
        }
    })
    .await
}

#[tauri::command]
pub async fn set_autostart(enabled: bool, app: tauri::AppHandle) -> Result<String, String> {
    run_blocking(move || {
        #[cfg(windows)]
        {
            use tauri_plugin_autostart::ManagerExt;
            if enabled {
                app.autolaunch().enable().map_err(|e| format!("enable autostart: {}", e))?;
                Ok("autostart enabled".into())
            } else {
                app.autolaunch().disable().map_err(|e| format!("disable autostart: {}", e))?;
                Ok("autostart disabled".into())
            }
        }
        #[cfg(not(windows))]
        {
            let _ = (&app, enabled);
            Err("autostart only available on Windows".into())
        }
    })
    .await
}
